# Generated by Django 2.2.7 on 2020-02-26 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiGames', '0002_auto_20200226_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
